// AUTO-GENERATED from Rivstart A1/A2 ordkort PDF.



export const RIVSTART_CHAPTERS = [
  { chapter: 1, cards: [
    { sv: "arbetar", en: "works" },
    { sv: "ett barn", en: "a child" },
    { sv: "bor", en: "lives" },
    { sv: "ett efternamn", en: "a surname" },
    { sv: "eller", en: "or" },
    { sv: "en flickvän", en: "a girlfriend" },
    { sv: "en fråga", en: "a question" },
    { sv: "från", en: "from" },
    { sv: "gift", en: "married" },
    { sv: "har", en: "has" },
    { sv: "heter", en: "is named" },
    { sv: "inte", en: "not" },
    { sv: "jobbar", en: "works" },
    { sv: "kommer", en: "comes" },
    { sv: "kul", en: "fun" },
    { sv: "ett land", en: "a country" },
    { sv: "ligger", en: "lies/is located" },
    { sv: "läser", en: "reads" },
    { sv: "men", en: "but" },
    { sv: "ett namn", en: "a name" },
    { sv: "nu", en: "now" },
    { sv: "och", en: "and" },
    { sv: "pluggar", en: "studies" },
    { sv: "en pojkvän", en: "a boyfriend" },
    { sv: "pratar", en: "talks" },
    { sv: "skriver", en: "writes" },
    { sv: "en son", en: "a son" },
    { sv: "ett språk", en: "a language" },
    { sv: "säger", en: "says" },
    { sv: "talar", en: "speaks" },
    { sv: "tittar", en: "looks/watches" },
    { sv: "ursäkta", en: "excuse me" },
    { sv: "vad", en: "what" },
    { sv: "var", en: "where/was" },
    { sv: "varifrån", en: "from where" },
    { sv: "är", en: "is/are" },
  ]},
  { chapter: 2, cards: [
    { sv: "dricker", en: "drinks" },
    { sv: "en fest", en: "a party" },
    { sv: "fin", en: "fine/nice" },
    { sv: "en flaska", en: "a bottle" },
    { sv: "förkyld", en: "having a cold" },
    { sv: "ganska", en: "quite" },
    { sv: "går", en: "goes/walks" },
    { sv: "gör", en: "does/makes" },
    { sv: "en handduk", en: "a towel" },
    { sv: "här", en: "here" },
    { sv: "igen", en: "again" },
    { sv: "intresserad", en: "interested" },
    { sv: "jättebra", en: "great" },
    { sv: "längtar", en: "longs for" },
    { sv: "en läxa", en: "a homework assignment" },
    { sv: "med", en: "with" },
    { sv: "mår", en: "feels (how are you)" },
    { sv: "en mössa", en: "a beanie/cap" },
    { sv: "också", en: "also" },
    { sv: "pengar", en: "money" },
    { sv: "rolig", en: "fun" },
    { sv: "en sak", en: "a thing" },
    { sv: "spelar", en: "plays" },
    { sv: "svår", en: "difficult" },
    { sv: "sådär", en: "so-so" },
    { sv: "såklart", en: "of course" },
    { sv: "tillsammans", en: "together" },
    { sv: "trivs", en: "feels at home" },
    { sv: "träffar", en: "meets" },
    { sv: "trött", en: "tired" },
    { sv: "varför", en: "why" },
    { sv: "välkommen", en: "welcome" },
    { sv: "en vän", en: "a friend" },
    { sv: "en väska", en: "a bag" },
    { sv: "åker", en: "goes/travels" },
    { sv: "ett äpple", en: "an apple" },
  ]},
  { chapter: 3, cards: [
    { sv: "börjar", en: "begins" },
    { sv: "en dag", en: "a day" },
    { sv: "en frukost", en: "a breakfast" },
    { sv: "frågar", en: "asks" },
    { sv: "född", en: "born" },
    { sv: "gillar", en: "likes" },
    { sv: "hungrig", en: "hungry" },
    { sv: "hur", en: "how" },
    { sv: "en kanelbulle", en: "a cinnamon bun" },
    { sv: "en kompis", en: "a friend" },
    { sv: "en kväll", en: "an evening" },
    { sv: "lyssnar", en: "listens" },
    { sv: "lägger sig", en: "goes to bed" },
    { sv: "en middag", en: "a dinner" },
    { sv: "en morgon", en: "a morning" },
    { sv: "många", en: "many" },
    { sv: "ny", en: "new" },
    { sv: "när", en: "when" },
    { sv: "ofta", en: "often" },
    { sv: "en pensionär", en: "a retiree" },
    { sv: "promenerar", en: "takes a walk" },
    { sv: "ringer", en: "calls" },
    { sv: "sedan", en: "then/since" },
    { sv: "sjuk", en: "sick" },
    { sv: "somnar", en: "falls asleep" },
    { sv: "sover", en: "sleeps" },
    { sv: "stor", en: "big" },
    { sv: "stänger", en: "closes" },
    { sv: "svarar", en: "answers" },
    { sv: "en tid", en: "a time" },
    { sv: "törstig", en: "thirsty" },
    { sv: "vaknar", en: "wakes up" },
    { sv: "vatten", en: "water" },
    { sv: "vilken", en: "which" },
    { sv: "äter", en: "eats" },
    { sv: "öppnar", en: "opens" },
  ]},
  { chapter: 4, cards: [
    { sv: "en affär", en: "a shop" },
    { sv: "alla", en: "all/everyone" },
    { sv: "alltid", en: "always" },
    { sv: "använder", en: "uses" },
    { sv: "en apelsin", en: "an orange" },
    { sv: "bakar", en: "bakes" },
    { sv: "behöver", en: "needs" },
    { sv: "berättar", en: "tells" },
    { sv: "betalar", en: "pays" },
    { sv: "en bild", en: "a picture" },
    { sv: "en bit", en: "a piece" },
    { sv: "en bokstav", en: "a letter" },
    { sv: "bra", en: "good" },
    { sv: "en citron", en: "a lemon" },
    { sv: "dricker", en: "drinks" },
    { sv: "där", en: "there" },
    { sv: "efter", en: "after" },
    { sv: "fikar", en: "has fika" },
    { sv: "finns", en: "there is/are" },
    { sv: "fyra", en: "four" },
    { sv: "först", en: "first" },
    { sv: "förstår", en: "understands" },
    { sv: "glad", en: "happy" },
    { sv: "en gurka", en: "a cucumber" },
    { sv: "går", en: "goes/walks" },
    { sv: "gärna", en: "gladly" },
    { sv: "gör", en: "does/makes" },
    { sv: "har", en: "has" },
    { sv: "(en) havremjölk", en: "oat milk" },
    { sv: "hjälper", en: "helps" },
    { sv: "en hylla", en: "a shelf" },
    { sv: "här", en: "here" },
    { sv: "höger", en: "right" },
    { sv: "ibland", en: "sometimes" },
    { sv: "en idé", en: "an idea" },
    { sv: "igen", en: "again" },
    { sv: "en kaka", en: "a cookie/cake" },
    { sv: "kan", en: "can" },
    { sv: "en klasskompis", en: "a classmate" },
    { sv: "en kollega", en: "a colleague" },
    { sv: "kommer", en: "comes" },
    { sv: "kontanter", en: "cash" },
    { sv: "ett kort", en: "a card" },
    { sv: "kostar", en: "costs" },
    { sv: "ett kvitto", en: "a receipt" },
    { sv: "köper", en: "buys" },
    { sv: "lite", en: "a little" },
    { sv: "lång", en: "long/tall" },
    { sv: "en läsk", en: "a soda" },
    { sv: "en läxa", en: "a homework assignment" },
    { sv: "mellan", en: "between" },
    { sv: "en middag", en: "a dinner" },
    { sv: "(ett) mjöl", en: "flour" },
    { sv: "måste", en: "must" },
    { sv: "ett paket", en: "a package" },
    { sv: "en plats", en: "a place" },
    { sv: "en purjolök", en: "a leek" },
    { sv: "ett päron", en: "a pear" },
    { sv: "ska", en: "shall/will" },
    { sv: "en sko", en: "a shoe" },
    { sv: "en smörgås", en: "a sandwich" },
    { sv: "(ett) socker", en: "sugar" },
    { sv: "stannar", en: "stops/stays" },
    { sv: "säljer", en: "sells" },
    { sv: "tar", en: "takes" },
    { sv: "vill", en: "wants" },
    { sv: "ett ägg", en: "an egg" },
    { sv: "en älg", en: "a moose" },
    { sv: "älskar", en: "loves" },
    { sv: "ett äpple", en: "an apple" },
    { sv: "äter", en: "eats" },
    { sv: "(ett) öl", en: "beer" },
  ]},
  { chapter: 5, cards: [
    { sv: "aldrig", en: "never" },
    { sv: "en bio", en: "a cinema" },
    { sv: "en blomma", en: "a flower" },
    { sv: "brukar", en: "usually" },
    { sv: "ett bär", en: "a berry" },
    { sv: "en dator", en: "a computer" },
    { sv: "en deckare", en: "a detective story" },
    { sv: "duschar", en: "showers" },
    { sv: "dålig", en: "bad" },
    { sv: "en eftermiddag", en: "an afternoon" },
    { sv: "fiskar", en: "fishes" },
    { sv: "en flod", en: "a river" },
    { sv: "forskar", en: "researches" },
    { sv: "en forskare", en: "a researcher" },
    { sv: "framför", en: "in front of" },
    { sv: "först", en: "first" },
    { sv: "glad", en: "happy" },
    { sv: "ett glas", en: "a glass" },
    { sv: "grönsaker", en: "vegetables" },
    { sv: "gör", en: "does/makes" },
    { sv: "handlar om", en: "is about" },
    { sv: "en hund", en: "a dog" },
    { sv: "hänger med", en: "keeps up/joins" },
    { sv: "ibland", en: "sometimes" },
    { sv: "ett intresse", en: "an interest" },
    { sv: "kanske", en: "maybe" },
    { sv: "klär på sig", en: "gets dressed" },
    { sv: "klättrar", en: "climbs" },
    { sv: "kollar", en: "checks" },
    { sv: "ett liv", en: "a life" },
    { sv: "en loppis", en: "a flea market" },
    { sv: "lugn", en: "calm" },
    { sv: "låter", en: "sounds/lets" },
    { sv: "en lägenhet", en: "an apartment" },
    { sv: "länge", en: "a long time" },
    { sv: "läskig", en: "scary" },
    { sv: "mat", en: "food" },
    { sv: "med", en: "with" },
    { sv: "myser", en: "cozies up" },
    { sv: "ett möte", en: "a meeting" },
    { sv: "en natt", en: "a night" },
    { sv: "ett nummer", en: "a number" },
    { sv: "olika", en: "different" },
    { sv: "planerar", en: "plans" },
    { sv: "romantisk", en: "romantic" },
    { sv: "samlar", en: "collects" },
    { sv: "en semester", en: "a vacation" },
    { sv: "en siffra", en: "a digit" },
    { sv: "självklart", en: "of course" },
    { sv: "en skorpa", en: "a rusk" },
    { sv: "en skräckfilm", en: "a horror film" },
    { sv: "slappar", en: "chills" },
    { sv: "slutar", en: "finishes" },
    { sv: "en sommarstuga", en: "a summer cottage" },
    { sv: "springer", en: "runs" },
    { sv: "en stad", en: "a city" },
    { sv: "en stund", en: "a while" },
    { sv: "stänger", en: "closes" },
    { sv: "sällan", en: "seldom" },
    { sv: "en tidning", en: "a newspaper" },
    { sv: "en timme", en: "an hour" },
    { sv: "en tisdag", en: "a Tuesday" },
    { sv: "en tjej", en: "a girl" },
    { sv: "torsdag", en: "Thursday" },
    { sv: "tråkig", en: "boring" },
    { sv: "en trädgård", en: "a garden" },
    { sv: "träffar", en: "meets" },
    { sv: "tycker om", en: "likes" },
    { sv: "tänker", en: "thinks" },
    { sv: "utan", en: "without" },
    { sv: "varje", en: "every" },
    { sv: "en vecka", en: "a week" },
  ]},
  { chapter: 6, cards: [
    { sv: "bara", en: "only/just" },
    { sv: "ett barnbarn", en: "a grandchild" },
    { sv: "berömd", en: "famous" },
    { sv: "betyder", en: "means" },
    { sv: "blir", en: "becomes" },
    { sv: "ett bonusbarn", en: "a stepchild" },
    { sv: "en bror", en: "a brother" },
    { sv: "bygger", en: "builds" },
    { sv: "båda", en: "both" },
    { sv: "delar", en: "shares" },
    { sv: "en dotter", en: "a daughter" },
    { sv: "drömmer", en: "dreams" },
    { sv: "dör", en: "dies" },
    { sv: "egen", en: "own" },
    { sv: "ett exempel", en: "an example" },
    { sv: "en fabrik", en: "a factory" },
    { sv: "en farbror", en: "an uncle (paternal)" },
    { sv: "en farfar", en: "a grandfather (paternal)" },
    { sv: "farlig", en: "dangerous" },
    { sv: "en faster", en: "an aunt (paternal)" },
    { sv: "flyttar", en: "moves" },
    { sv: "fortsätter", en: "continues" },
    { sv: "en fru", en: "a wife" },
    { sv: "följer med", en: "comes along" },
    { sv: "en författare", en: "an author" },
    { sv: "en förskola", en: "a preschool" },
    { sv: "en förälder", en: "a parent" },
    { sv: "gammal", en: "old" },
    { sv: "ganska", en: "quite" },
    { sv: "en gruva", en: "a mine" },
    { sv: "en gäst", en: "a guest" },
    { sv: "ett halvsyskon", en: "a half-sibling" },
    { sv: "en helg", en: "a weekend" },
    { sv: "hör", en: "hears" },
    { sv: "i höstas", en: "last autumn" },
    { sv: "ibland", en: "sometimes" },
    { sv: "en journalist", en: "a journalist" },
    { sv: "(ett) klimat", en: "climate" },
    { sv: "ett krig", en: "a war" },
    { sv: "en kung", en: "a king" },
    { sv: "en kusin", en: "a cousin" },
    { sv: "känd", en: "known/famous" },
    { sv: "känner", en: "knows/feels" },
    { sv: "köper", en: "buys" },
    { sv: "en man", en: "a man/husband" },
    { sv: "mellan", en: "between" },
    { sv: "en morbror", en: "an uncle (maternal)" },
    { sv: "en morfar", en: "a grandfather (maternal)" },
    { sv: "en mormor", en: "a grandmother (maternal)" },
    { sv: "en moster", en: "an aunt (maternal)" },
    { sv: "nähä!", en: "oh really!" },
    { sv: "nästan", en: "almost" },
    { sv: "pluggar", en: "studies" },
    { sv: "ett pris", en: "a price/prize" },
    { sv: "reser", en: "travels" },
    { sv: "en skådespelare", en: "an actor" },
    { sv: "en släkt", en: "a family/relatives" },
    { sv: "ett stipendium", en: "a scholarship" },
    { sv: "en svägerska", en: "a sister-in-law" },
    { sv: "ett syskon", en: "a sibling" },
    { sv: "en syster", en: "a sister" },
    { sv: "sällan", en: "seldom" },
    { sv: "tillbaka", en: "back" },
    { sv: "tjänar", en: "earns" },
    { sv: "vacker", en: "beautiful" },
    { sv: "ett vapen", en: "a weapon" },
    { sv: "en vecka", en: "a week" },
    { sv: "viktig", en: "important" },
    { sv: "en värld", en: "a world" },
    { sv: "åker", en: "goes/travels" },
    { sv: "ett år", en: "a year" },
    { sv: "öppen", en: "open" },
  ]},
  { chapter: 7, cards: [
    { sv: "en avdelning", en: "a department" },
    { sv: "ett bestick", en: "cutlery" },
    { sv: "billig", en: "cheap" },
    { sv: "blommig", en: "flowery" },
    { sv: "(en) bomull", en: "cotton" },
    { sv: "brun", en: "brown" },
    { sv: "byxor", en: "trousers" },
    { sv: "drömmer", en: "dreams" },
    { sv: "dyr", en: "expensive" },
    { sv: "ett erbjudande", en: "an offer" },
    { sv: "ful", en: "ugly" },
    { sv: "en färg", en: "a color" },
    { sv: "förra", en: "previous" },
    { sv: "en gaffel", en: "a fork" },
    { sv: "en garanti", en: "a guarantee" },
    { sv: "en gardin", en: "a curtain" },
    { sv: "ger", en: "gives" },
    { sv: "glad", en: "happy" },
    { sv: "god", en: "good/tasty" },
    { sv: "en grej", en: "a thing" },
    { sv: "en gryta", en: "a pot/stew" },
    { sv: "gul", en: "yellow" },
    { sv: "hemma", en: "at home" },
    { sv: "hård", en: "hard" },
    { sv: "ingen", en: "no one/none" },
    { sv: "jämför", en: "compares" },
    { sv: "en kastrull", en: "a saucepan" },
    { sv: "kläder", en: "clothes" },
    { sv: "en klänning", en: "a dress" },
    { sv: "en kniv", en: "a knife" },
    { sv: "en kollega", en: "a colleague" },
    { sv: "kontrollerar", en: "controls/checks" },
    { sv: "en kudde", en: "a pillow" },
    { sv: "en kvalitet", en: "a quality" },
    { sv: "ett kök", en: "a kitchen" },
    { sv: "(en) köttfärssås", en: "minced meat sauce" },
    { sv: "lagar", en: "cooks/fixes" },
    { sv: "ett lakan", en: "a sheet" },
    { sv: "letar", en: "looks for" },
    { sv: "lång", en: "long/tall" },
    { sv: "lätt", en: "easy/light" },
    { sv: "löparskor", en: "running shoes" },
    { sv: "en madrass", en: "a mattress" },
    { sv: "en medlem", en: "a member" },
    { sv: "mjuk", en: "soft" },
    { sv: "mörk", en: "dark" },
    { sv: "någon", en: "someone" },
    { sv: "nästan", en: "almost" },
    { sv: "omodern", en: "old-fashioned" },
    { sv: "passar", en: "fits/suits" },
    { sv: "populär", en: "popular" },
    { sv: "en resväska", en: "a suitcase" },
    { sv: "rolig", en: "fun" },
    { sv: "räcker", en: "is enough" },
    { sv: "röd", en: "red" },
    { sv: "en sked", en: "a spoon" },
    { sv: "en sko", en: "a shoe" },
    { sv: "en skog", en: "a forest" },
    { sv: "skön", en: "comfortable/nice" },
    { sv: "smal", en: "thin" },
    { sv: "snygg", en: "good-looking" },
    { sv: "en storlek", en: "a size" },
    { sv: "ställer", en: "puts/places" },
    { sv: "svart", en: "black" },
    { sv: "en säng", en: "a bed" },
    { sv: "en sänglampa", en: "a bedside lamp" },
    { sv: "en tröja", en: "a sweater" },
    { sv: "tyvärr", en: "unfortunately" },
    { sv: "utan", en: "without" },
    { sv: "verkligen", en: "really" },
    { sv: "vet", en: "knows" },
    { sv: "ett ögonblick", en: "a moment" },
  ]},
  { chapter: 8, cards: [
    { sv: "en aktivitet", en: "an activity" },
    { sv: "badar", en: "bathes/swims" },
    { sv: "behöver", en: "needs" },
    { sv: "blåser", en: "blows/is windy" },
    { sv: "bokar", en: "books" },
    { sv: "borde", en: "should" },
    { sv: "ett datum", en: "a date" },
    { sv: "(en) dimma", en: "fog" },
    { sv: "fantastisk", en: "fantastic" },
    { sv: "får", en: "gets/may" },
    { sv: "en födelsedag", en: "a birthday" },
    { sv: "ett fönster", en: "a window" },
    { sv: "försöker", en: "tries" },
    { sv: "en grad", en: "a degree" },
    { sv: "Grattis!", en: "Congratulations!" },
    { sv: "gummistövlar", en: "rubber boots" },
    { sv: "hinner", en: "has time" },
    { sv: "hoppar", en: "jumps" },
    { sv: "hoppas", en: "hopes" },
    { sv: "hos", en: "at (someone's place)" },
    { sv: "håller med", en: "agrees" },
    { sv: "härlig", en: "lovely" },
    { sv: "kall", en: "cold" },
    { sv: "en kille", en: "a guy" },
    { sv: "en konsert", en: "a concert" },
    { sv: "konstig", en: "strange" },
    { sv: "köttbullar", en: "meatballs" },
    { sv: "lingonsylt", en: "lingonberry jam" },
    { sv: "ett liv", en: "a life" },
    { sv: "missar", en: "misses" },
    { sv: "modig", en: "brave" },
    { sv: "molnig", en: "cloudy" },
    { sv: "mulen", en: "overcast" },
    { sv: "ett myggmedel", en: "a mosquito repellent" },
    { sv: "norr", en: "north" },
    { sv: "ofta", en: "often" },
    { sv: "orkar", en: "has the energy" },
    { sv: "packar", en: "packs" },
    { sv: "planerar", en: "plans" },
    { sv: "en plats", en: "a place" },
    { sv: "en plusgrad", en: "a degree above zero" },
    { sv: "potatismos", en: "mashed potatoes" },
    { sv: "en present", en: "a gift" },
    { sv: "en prinsesstårta", en: "a princess cake" },
    { sv: "på förmiddagen", en: "in the late morning" },
    { sv: "ett regn", en: "rain" },
    { sv: "regnar", en: "rains" },
    { sv: "en regnjacka", en: "a rain jacket" },
    { sv: "en resa", en: "a trip" },
    { sv: "ett rum", en: "a room" },
    { sv: "rädd", en: "afraid" },
    { sv: "röker", en: "smokes" },
    { sv: "sjunger", en: "sings" },
    { sv: "skiner", en: "shines" },
    { sv: "en skärgård", en: "an archipelago" },
    { sv: "snart", en: "soon" },
    { sv: "(en) snö", en: "snow" },
    { sv: "snöar", en: "snows" },
    { sv: "solig", en: "sunny" },
    { sv: "sparar", en: "saves" },
    { sv: "spännande", en: "exciting" },
    { sv: "ett ställe", en: "a place" },
    { sv: "söder", en: "south" },
    { sv: "en temperatur", en: "a temperature" },
    { sv: "en timme", en: "an hour" },
    { sv: "tränar", en: "trains" },
    { sv: "underbar", en: "wonderful" },
    { sv: "varm", en: "warm" },
    { sv: "en väderprognos", en: "a weather forecast" },
    { sv: "åskar", en: "thunders" },
    { sv: "övar", en: "practices" },
    { sv: "överallt", en: "everywhere" },
  ]},
  { chapter: 9, cards: [
    { sv: "ett bageri", en: "a bakery" },
    { sv: "betalar", en: "pays" },
    { sv: "bredvid", en: "next to" },
    { sv: "byter", en: "changes/swaps" },
    { sv: "cyklar", en: "cycles" },
    { sv: "ett dopp", en: "a dip/swim" },
    { sv: "dyr", en: "expensive" },
    { sv: "enkel", en: "simple" },
    { sv: "festar", en: "parties" },
    { sv: "finns", en: "there is/are" },
    { sv: "en fisk", en: "a fish" },
    { sv: "ett fjäll", en: "a mountain (fjäll)" },
    { sv: "ett flyg", en: "a flight" },
    { sv: "en flygplats", en: "an airport" },
    { sv: "en fot", en: "a foot" },
    { sv: "frisk", en: "healthy" },
    { sv: "en färja", en: "a ferry" },
    { sv: "färsk", en: "fresh" },
    { sv: "försenad", en: "delayed" },
    { sv: "ett förslag", en: "a suggestion" },
    { sv: "gata", en: "street" },
    { sv: "en glass", en: "an ice cream" },
    { sv: "hemifrån", en: "from home" },
    { sv: "en hiss", en: "an elevator" },
    { sv: "hungrig", en: "hungry" },
    { sv: "en huvudstad", en: "a capital city" },
    { sv: "en hållplats", en: "a (bus) stop" },
    { sv: "i morse", en: "this morning" },
    { sv: "en karta", en: "a map" },
    { sv: "kopplar av", en: "relaxes" },
    { sv: "en korsning", en: "an intersection" },
    { sv: "en kust", en: "a coast" },
    { sv: "en kvart", en: "a quarter (15 min)" },
    { sv: "en kyrka", en: "a church" },
    { sv: "laddar ner", en: "downloads" },
    { sv: "ett landskap", en: "a landscape/province" },
    { sv: "(en) luft", en: "air" },
    { sv: "en moské", en: "a mosque" },
    { sv: "mysig", en: "cozy" },
    { sv: "en månad", en: "a month" },
    { sv: "en nyhet", en: "a news item" },
    { sv: "nära", en: "near" },
    { sv: "nästa", en: "next" },
    { sv: "en park", en: "a park" },
    { sv: "ett pendeltåg", en: "a commuter train" },
    { sv: "en promenad", en: "a walk" },
    { sv: "rakt fram", en: "straight ahead" },
    { sv: "redan", en: "already" },
    { sv: "en räka", en: "a shrimp" },
    { sv: "(en) sand", en: "sand" },
    { sv: "en semester", en: "a vacation" },
    { sv: "shoppar", en: "shops" },
    { sv: "en sjö", en: "a lake" },
    { sv: "en skoaffär", en: "a shoe shop" },
    { sv: "en storstad", en: "a big city" },
    { sv: "en strand", en: "a beach" },
    { sv: "en synagoga", en: "a synagogue" },
    { sv: "ett tempel", en: "a temple" },
    { sv: "tidigt", en: "early" },
    { sv: "en tunnelbana", en: "a subway" },
    { sv: "en tå", en: "a toe" },
    { sv: "ett tåg", en: "a train" },
    { sv: "ett tält", en: "a tent" },
    { sv: "ungefär", en: "approximately" },
    { sv: "utanför", en: "outside" },
    { sv: "en utsikt", en: "a view" },
    { sv: "en vagn", en: "a wagon/car" },
    { sv: "en våning", en: "a floor/apartment" },
    { sv: "väntar", en: "waits" },
    { sv: "en älskling", en: "a darling" },
    { sv: "en ö", en: "an island" },
    { sv: "ett övergångsställe", en: "a crosswalk" },
  ]},
  { chapter: 10, cards: [
    { sv: "alla", en: "all/everyone" },
    { sv: "andra", en: "other/second" },
    { sv: "använder", en: "uses" },
    { sv: "en artist", en: "an artist" },
    { sv: "bara", en: "only/just" },
    { sv: "en befolkning", en: "a population" },
    { sv: "behöver", en: "needs" },
    { sv: "ett berg", en: "a mountain" },
    { sv: "en blandning", en: "a mixture" },
    { sv: "en bokstav", en: "a letter" },
    { sv: "bredvid", en: "next to" },
    { sv: "båda", en: "both" },
    { sv: "en del", en: "a part" },
    { sv: "därför", en: "therefore" },
    { sv: "enkel", en: "simple" },
    { sv: "en EU-medborgare", en: "an EU citizen" },
    { sv: "fattig", en: "poor" },
    { sv: "ett fjäll", en: "a mountain (fjäll)" },
    { sv: "en flykting", en: "a refugee" },
    { sv: "flyttar", en: "moves" },
    { sv: "först", en: "first" },
    { sv: "försöker", en: "tries" },
    { sv: "ganska", en: "quite" },
    { sv: "en gräns", en: "a border" },
    { sv: "gullig", en: "cute" },
    { sv: "en halvö", en: "a peninsula" },
    { sv: "hemsk", en: "terrible" },
    { sv: "en huvudstad", en: "a capital city" },
    { sv: "högutbildad", en: "highly educated" },
    { sv: "hör", en: "hears" },
    { sv: "en invånare", en: "an inhabitant" },
    { sv: "en kommun", en: "a municipality" },
    { sv: "konstig", en: "strange" },
    { sv: "känd", en: "known/famous" },
    { sv: "känner", en: "knows/feels" },
    { sv: "en lastbil", en: "a truck" },
    { sv: "lever", en: "lives" },
    { sv: "ligger", en: "lies/is located" },
    { sv: "en människa", en: "a human" },
    { sv: "nästan", en: "almost" },
    { sv: "platt", en: "flat" },
    { sv: "plockar", en: "picks" },
    { sv: "rätt", en: "right/correct" },
    { sv: "samtidigt", en: "at the same time" },
    { sv: "en sjö", en: "a lake" },
    { sv: "en skog", en: "a forest" },
    { sv: "slutar", en: "finishes" },
    { sv: "ett språk", en: "a language" },
    { sv: "stannar", en: "stops/stays" },
    { sv: "ett stål", en: "steel" },
    { sv: "stängd", en: "closed" },
    { sv: "svår", en: "difficult" },
    { sv: "söker asyl", en: "seeks asylum" },
    { sv: "(ett) sötvatten", en: "fresh water" },
    { sv: "tiotusentals", en: "tens of thousands" },
    { sv: "tätbefolkad", en: "densely populated" },
    { sv: "ungefär", en: "approximately" },
    { sv: "ett ursprungsfolk", en: "an indigenous people" },
    { sv: "utanför", en: "outside" },
    { sv: "en utbytesstudent", en: "an exchange student" },
    { sv: "utomlands", en: "abroad" },
    { sv: "utvecklar", en: "develops" },
    { sv: "varandra", en: "each other" },
    { sv: "ett vattendrag", en: "a waterway" },
    { sv: "verkligen", en: "really" },
    { sv: "vet", en: "knows" },
    { sv: "viktig", en: "important" },
    { sv: "en yta", en: "a surface" },
    { sv: "ändrar", en: "changes" },
    { sv: "även", en: "also" },
    { sv: "en ö", en: "an island" },
    { sv: "öppnar", en: "opens" },
  ]},
  { chapter: 11, cards: [
    { sv: "annars", en: "otherwise" },
    { sv: "berättar", en: "tells" },
    { sv: "bjuder hem", en: "invites home" },
    { sv: "en dator", en: "a computer" },
    { sv: "ett djur", en: "an animal" },
    { sv: "duktig", en: "skilled/good at" },
    { sv: "ensam", en: "alone" },
    { sv: "faktiskt", en: "actually" },
    { sv: "en frys", en: "a freezer" },
    { sv: "frånskild", en: "divorced" },
    { sv: "fungerar", en: "works/functions" },
    { sv: "fyller år", en: "has a birthday" },
    { sv: "får", en: "gets/may" },
    { sv: "följer", en: "follows" },
    { sv: "förbjuden", en: "forbidden" },
    { sv: "en förklaring", en: "an explanation" },
    { sv: "förstås", en: "of course" },
    { sv: "förut", en: "before/previously" },
    { sv: "ganska", en: "quite" },
    { sv: "glömmer", en: "forgets" },
    { sv: "gullig", en: "cute" },
    { sv: "en gång", en: "a time/once" },
    { sv: "en gård", en: "a yard/farm" },
    { sv: "hittar", en: "finds" },
    { sv: "hoppas", en: "hopes" },
    { sv: "händer", en: "happens" },
    { sv: "hänger", en: "hangs" },
    { sv: "härlig", en: "lovely" },
    { sv: "en idé", en: "an idea" },
    { sv: "en inbjudan", en: "an invitation" },
    { sv: "ingenting", en: "nothing" },
    { sv: "ett intresse", en: "an interest" },
    { sv: "klickar", en: "clicks" },
    { sv: "kör", en: "drives" },
    { sv: "ett körkort", en: "a driver's license" },
    { sv: "leker", en: "plays" },
    { sv: "ett ljud", en: "a sound" },
    { sv: "ljuger", en: "lies (untruth)" },
    { sv: "loggar in", en: "logs in" },
    { sv: "lånar", en: "borrows/lends" },
    { sv: "en lägenhet", en: "an apartment" },
    { sv: "lämnar tillbaka", en: "returns" },
    { sv: "en länk", en: "a link" },
    { sv: "en löpning", en: "a run" },
    { sv: "ett lösenord", en: "a password" },
    { sv: "en nybörjarkurs", en: "a beginner course" },
    { sv: "en papperskorg", en: "a trash bin" },
    { sv: "en partner", en: "a partner" },
    { sv: "ett pälsdjur", en: "a furry pet" },
    { sv: "rolig", en: "fun" },
    { sv: "saknar", en: "misses" },
    { sv: "en skrivare", en: "a printer" },
    { sv: "skriver ut", en: "prints" },
    { sv: "en skärm", en: "a screen" },
    { sv: "en snygging", en: "a good-looking person" },
    { sv: "startar om", en: "restarts" },
    { sv: "ett streck", en: "a line/dash" },
    { sv: "stänger", en: "closes" },
    { sv: "säljer", en: "sells" },
    { sv: "sätter på", en: "turns on" },
    { sv: "en tavla", en: "a painting" },
    { sv: "en tidning", en: "a newspaper" },
    { sv: "tillbaka", en: "back" },
    { sv: "tipsar", en: "gives tips" },
    { sv: "trasig", en: "broken" },
    { sv: "trevlig", en: "pleasant" },
    { sv: "trist", en: "dull/sad" },
    { sv: "tråkig", en: "boring" },
    { sv: "tvättar", en: "washes" },
    { sv: "ett uteliv", en: "nightlife" },
    { sv: "en utställning", en: "an exhibition" },
    { sv: "en väg", en: "a road" },
  ]},
  { chapter: 12, cards: [
    { sv: "alkoholfri", en: "non-alcoholic" },
    { sv: "använder", en: "uses" },
    { sv: "beställer", en: "orders" },
    { sv: "ett blåbär", en: "a blueberry" },
    { sv: "en bondgård", en: "a farm" },
    { sv: "ett bröd", en: "a bread" },
    { sv: "ett bröllop", en: "a wedding" },
    { sv: "en dryck", en: "a drink" },
    { sv: "eftersom", en: "because" },
    { sv: "en favoriträtt", en: "a favourite dish" },
    { sv: "(ett) fläsk", en: "pork" },
    { sv: "fryst", en: "frozen" },
    { sv: "en fågel", en: "a bird" },
    { sv: "färsk", en: "fresh" },
    { sv: "handlar", en: "shops" },
    { sv: "hemlagad", en: "homemade" },
    { sv: "en hundring", en: "a hundred-kronor note" },
    { sv: "en husmanskost", en: "home-style food" },
    { sv: "en huvudrätt", en: "a main course" },
    { sv: "(en) hämtmat", en: "takeout food" },
    { sv: "hög", en: "high" },
    { sv: "ingår", en: "is included" },
    { sv: "inlagd", en: "pickled" },
    { sv: "inte förrän", en: "not until" },
    { sv: "en jordgubbe", en: "a strawberry" },
    { sv: "kallas", en: "is called" },
    { sv: "ett knäckebröd", en: "a crispbread" },
    { sv: "en korv", en: "a sausage" },
    { sv: "ledsen", en: "sad" },
    { sv: "en lukt", en: "a smell" },
    { sv: "en matlagning", en: "cooking" },
    { sv: "en maträtt", en: "a dish" },
    { sv: "mjuk", en: "soft" },
    { sv: "mogen", en: "ripe" },
    { sv: "passar", en: "fits/suits" },
    { sv: "plockar", en: "picks" },
    { sv: "rak", en: "straight" },
    { sv: "en rotfrukt", en: "a root vegetable" },
    { sv: "en råvara", en: "a raw ingredient" },
    { sv: "räknar", en: "counts" },
    { sv: "sen", en: "late" },
    { sv: "sista", en: "last" },
    { sv: "själv", en: "self" },
    { sv: "ett skafferi", en: "a pantry" },
    { sv: "ett skaldjur", en: "a shellfish" },
    { sv: "smakar", en: "tastes" },
    { sv: "en smula", en: "a crumb" },
    { sv: "stark", en: "strong" },
    { sv: "ett ställe", en: "a place" },
    { sv: "sugen på", en: "in the mood for" },
    { sv: "en svamp", en: "a mushroom" },
    { sv: "(en) sylt", en: "jam" },
    { sv: "säger", en: "says" },
    { sv: "sänker", en: "lowers" },
    { sv: "tackar", en: "thanks" },
    { sv: "ett torg", en: "a square" },
    { sv: "torkar", en: "wipes/dries" },
    { sv: "tror", en: "believes" },
    { sv: "tunn", en: "thin" },
    { sv: "tycker", en: "thinks/feels" },
    { sv: "tyvärr", en: "unfortunately" },
    { sv: "ungefär", en: "approximately" },
    { sv: "vanlig", en: "common/usual" },
    { sv: "varje", en: "every" },
    { sv: "ett vete", en: "wheat" },
    { sv: "en vinter", en: "a winter" },
    { sv: "väger", en: "weighs" },
    { sv: "en värme", en: "warmth" },
    { sv: "växer", en: "grows" },
    { sv: "en åsikt", en: "an opinion" },
    { sv: "äcklig", en: "disgusting" },
    { sv: "även", en: "also" },
  ]},
  { chapter: 13, cards: [
    { sv: "en arbetsdag", en: "a workday" },
    { sv: "en arbetsuppgift", en: "a work task" },
    { sv: "behöver", en: "needs" },
    { sv: "bifogar", en: "attaches" },
    { sv: "en bilmekaniker", en: "a car mechanic" },
    { sv: "bredvid", en: "next to" },
    { sv: "bråkar", en: "quarrels" },
    { sv: "byter", en: "changes/swaps" },
    { sv: "dammsuger", en: "vacuums" },
    { sv: "en dessert", en: "a dessert" },
    { sv: "diskar", en: "does the dishes" },
    { sv: "dukar", en: "sets the table" },
    { sv: "ensam", en: "alone" },
    { sv: "fortsätter", en: "continues" },
    { sv: "framme", en: "arrived/in front" },
    { sv: "ett företag", en: "a company" },
    { sv: "en förmiddag", en: "a morning (forenoon)" },
    { sv: "en förskollärare", en: "a preschool teacher" },
    { sv: "försover sig", en: "oversleeps" },
    { sv: "genom", en: "through" },
    { sv: "gissar", en: "guesses" },
    { sv: "en gäst", en: "a guest" },
    { sv: "en helg", en: "a weekend" },
    { sv: "hinner", en: "has time" },
    { sv: "hjälper", en: "helps" },
    { sv: "hämtar", en: "picks up" },
    { sv: "händig", en: "handy" },
    { sv: "i förrgår", en: "the day before yesterday" },
    { sv: "i morse", en: "this morning" },
    { sv: "konstig", en: "strange" },
    { sv: "en konstnär", en: "an artist" },
    { sv: "kreativ", en: "creative" },
    { sv: "en kund", en: "a customer" },
    { sv: "ledig", en: "free/off" },
    { sv: "en lista", en: "a list" },
    { sv: "en lägenhet", en: "an apartment" },
    { sv: "lämnar", en: "leaves" },
    { sv: "magisk", en: "magical" },
    { sv: "en medarbetare", en: "a coworker" },
    { sv: "en middag", en: "a dinner" },
    { sv: "nervös", en: "nervous" },
    { sv: "noggrann", en: "careful" },
    { sv: "ett norrsken", en: "northern lights" },
    { sv: "ett par", en: "a pair" },
    { sv: "en park", en: "a park" },
    { sv: "ett projekt", en: "a project" },
    { sv: "en saga", en: "a fairy tale" },
    { sv: "en sak", en: "a thing" },
    { sv: "ser", en: "sees" },
    { sv: "själv", en: "self" },
    { sv: "en skida", en: "a ski" },
    { sv: "skyndar sig", en: "hurries" },
    { sv: "snabb", en: "fast" },
    { sv: "en snickare", en: "a carpenter" },
    { sv: "social", en: "social" },
    { sv: "stark", en: "strong" },
    { sv: "stressig", en: "stressful" },
    { sv: "står", en: "stands" },
    { sv: "städar", en: "cleans" },
    { sv: "en tidning", en: "a newspaper" },
    { sv: "tillsammans", en: "together" },
    { sv: "trivs", en: "feels at home" },
    { sv: "en trädgårdsmäs- tare", en: "a gardener" },
    { sv: "under", en: "under" },
    { sv: "undrar", en: "wonders" },
    { sv: "en uppsats", en: "an essay" },
    { sv: "vaknar", en: "wakes up" },
    { sv: "vandrar", en: "hikes" },
    { sv: "varandra", en: "each other" },
    { sv: "väntar", en: "waits" },
    { sv: "en växt", en: "a plant" },
    { sv: "ett yrke", en: "a profession" },
  ]},
  { chapter: 14, cards: [
    { sv: "barfota", en: "barefoot" },
    { sv: "ett blåbär", en: "a blueberry" },
    { sv: "blåser", en: "blows/is windy" },
    { sv: "en bottenvåning", en: "a ground floor" },
    { sv: "en båt", en: "a boat" },
    { sv: "en dröm", en: "a dream" },
    { sv: "en dörr", en: "a door" },
    { sv: "en efterrätt", en: "a dessert" },
    { sv: "faktiskt", en: "actually" },
    { sv: "en fantasi", en: "an imagination" },
    { sv: "firar", en: "celebrates" },
    { sv: "ett fritidshus", en: "a holiday house" },
    { sv: "fryser", en: "freezes/is cold" },
    { sv: "en färja", en: "a ferry" },
    { sv: "före", en: "before" },
    { sv: "förlåt", en: "sorry" },
    { sv: "ett försäkringsbolag", en: "an insurance company" },
    { sv: "förut", en: "before/previously" },
    { sv: "gifter sig", en: "gets married" },
    { sv: "gissar", en: "guesses" },
    { sv: "glittrar", en: "glitters" },
    { sv: "glömmer", en: "forgets" },
    { sv: "en granne", en: "a neighbor" },
    { sv: "grillar", en: "grills" },
    { sv: "ett gräs", en: "grass" },
    { sv: "ett hav", en: "a sea" },
    { sv: "en helg", en: "a weekend" },
    { sv: "hugger", en: "chops" },
    { sv: "ifall", en: "in case" },
    { sv: "en inbjudan", en: "an invitation" },
    { sv: "jobbig", en: "tough" },
    { sv: "jämför", en: "compares" },
    { sv: "en kavaj", en: "a blazer" },
    { sv: "klipper", en: "cuts" },
    { sv: "en kopp", en: "a cup" },
    { sv: "kvar", en: "left/remaining" },
    { sv: "luktar", en: "smells" },
    { sv: "medan", en: "while" },
    { sv: "missar", en: "misses" },
    { sv: "en mås", en: "a seagull" },
    { sv: "naken", en: "naked" },
    { sv: "orkar", en: "has the energy" },
    { sv: "parkerar", en: "parks" },
    { sv: "plockar", en: "picks" },
    { sv: "regnar", en: "rains" },
    { sv: "ropar", en: "shouts" },
    { sv: "en rygg", en: "a back" },
    { sv: "röd", en: "red" },
    { sv: "sitter", en: "sits" },
    { sv: "skiner", en: "shines" },
    { sv: "skjuter", en: "shoots/pushes" },
    { sv: "skriker", en: "screams" },
    { sv: "Skål!", en: "Cheers!" },
    { sv: "en skärgård", en: "an archipelago" },
    { sv: "en släkting", en: "a relative" },
    { sv: "snygg", en: "good-looking" },
    { sv: "ett snöre", en: "a string" },
    { sv: "solar", en: "suns" },
    { sv: "spelar", en: "plays" },
    { sv: "spännande", en: "exciting" },
    { sv: "en stund", en: "a while" },
    { sv: "sur", en: "sour/grumpy" },
    { sv: "trots att", en: "despite" },
    { sv: "tvättar", en: "washes" },
    { sv: "valfri", en: "optional" },
    { sv: "varannan", en: "every other" },
    { sv: "verkligen", en: "really" },
    { sv: "vilar", en: "rests" },
    { sv: "vänlig", en: "kind" },
    { sv: "en älg", en: "a moose" },
    { sv: "äntligen", en: "finally" },
    { sv: "över", en: "over" },
  ]},
  { chapter: 15, cards: [
    { sv: "1800-talet", en: "the 19th century" },
    { sv: "använder", en: "uses" },
    { sv: "ett berg", en: "a mountain" },
    { sv: "beskriver", en: "describes" },
    { sv: "bredvid", en: "next to" },
    { sv: "en bubbla", en: "a bubble" },
    { sv: "en by", en: "a village" },
    { sv: "ett datum", en: "a date" },
    { sv: "döper", en: "names/baptizes" },
    { sv: "ett efternamn", en: "a surname" },
    { sv: "egentligen", en: "actually" },
    { sv: "ensam", en: "alone" },
    { sv: "en flygplats", en: "an airport" },
    { sv: "en frys", en: "a freezer" },
    { sv: "en födelsedag", en: "a birthday" },
    { sv: "ett förnamn", en: "a first name" },
    { sv: "försvinner", en: "disappears" },
    { sv: "förvånad", en: "surprised" },
    { sv: "golv", en: "floor" },
    { sv: "en gran", en: "a spruce" },
    { sv: "en hamster", en: "a hamster" },
    { sv: "hjälper", en: "helps" },
    { sv: "hänger", en: "hangs" },
    { sv: "en idrottare", en: "an athlete" },
    { sv: "ingenting", en: "nothing" },
    { sv: "en invånare", en: "an inhabitant" },
    { sv: "kallar", en: "calls (names)" },
    { sv: "klättrar", en: "climbs" },
    { sv: "en kommun", en: "a municipality" },
    { sv: "känns", en: "feels" },
    { sv: "ledig", en: "free/off" },
    { sv: "en leksak", en: "a toy" },
    { sv: "ett ljud", en: "a sound" },
    { sv: "ett ljus", en: "a light/candle" },
    { sv: "en lägenhet", en: "an apartment" },
    { sv: "matar", en: "feeds" },
    { sv: "minns", en: "remembers" },
    { sv: "missförstår", en: "misunderstands" },
    { sv: "myser", en: "cozies up" },
    { sv: "märker", en: "notices" },
    { sv: "mörk", en: "dark" },
    { sv: "nuförtiden", en: "nowadays" },
    { sv: "en nyckel", en: "a key" },
    { sv: "någonting", en: "something" },
    { sv: "okänd", en: "unknown" },
    { sv: "ovanlig", en: "unusual" },
    { sv: "en papegoja", en: "a parrot" },
    { sv: "en parkering", en: "a parking lot" },
    { sv: "en plats", en: "a place" },
    { sv: "redan", en: "already" },
    { sv: "självständig", en: "independent" },
    { sv: "en skog", en: "a forest" },
    { sv: "skrattar", en: "laughs" },
    { sv: "en släkting", en: "a relative" },
    { sv: "ett smeknamn", en: "a nickname" },
    { sv: "småpratar", en: "makes small talk" },
    { sv: "en spårvagn", en: "a tram" },
    { sv: "stannar", en: "stops/stays" },
    { sv: "en sten", en: "a stone" },
    { sv: "en strand", en: "a beach" },
    { sv: "ställer", en: "puts/places" },
    { sv: "suckar", en: "sighs" },
    { sv: "synd", en: "a pity" },
    { sv: "säker", en: "sure/safe" },
    { sv: "tappar", en: "drops" },
    { sv: "en tavla", en: "a painting" },
    { sv: "tidig", en: "early" },
    { sv: "tyst", en: "quiet" },
    { sv: "vandrar", en: "hikes" },
    { sv: "vattnar", en: "waters" },
    { sv: "verkligen", en: "really" },
    { sv: "väljer", en: "chooses" },
  ]},
  { chapter: 16, cards: [
    { sv: "antecknar", en: "takes notes" },
    { sv: "ett arbetsliv", en: "a working life" },
    { sv: "en arbetsplats", en: "a workplace" },
    { sv: "bestämmer", en: "decides" },
    { sv: "betalar", en: "pays" },
    { sv: "ett betyg", en: "a grade" },
    { sv: "bredvid", en: "next to" },
    { sv: "en diskussion", en: "a discussion" },
    { sv: "duktig", en: "skilled/good at" },
    { sv: "efteråt", en: "afterwards" },
    { sv: "egentligen", en: "actually" },
    { sv: "en folkhögskola", en: "a folk high school" },
    { sv: "en framtid", en: "a future" },
    { sv: "ett fritids", en: "after-school care" },
    { sv: "färdig", en: "finished" },
    { sv: "en föreläsning", en: "a lecture" },
    { sv: "förklarar", en: "explains" },
    { sv: "gratis", en: "free of charge" },
    { sv: "hoppar av", en: "drops out" },
    { sv: "en högskola", en: "a college" },
    { sv: "i början", en: "in the beginning" },
    { sv: "i genomsnitt", en: "on average" },
    { sv: "innehåller", en: "contains" },
    { sv: "en klasskompis", en: "a classmate" },
    { sv: "kostnadsfri", en: "free of charge" },
    { sv: "lånar", en: "borrows/lends" },
    { sv: "lär sig", en: "learns" },
    { sv: "en möjlighet", en: "a possibility" },
    { sv: "en nivå", en: "a level" },
    { sv: "nästa", en: "next" },
    { sv: "obligatorisk", en: "mandatory" },
    { sv: "olika", en: "different" },
    { sv: "ordning", en: "order" },
    { sv: "orkar", en: "has the energy" },
    { sv: "orättvis", en: "unfair" },
    { sv: "peppar", en: "motivates/pepper" },
    { sv: "pluggar", en: "studies" },
    { sv: "ett prov", en: "a test" },
    { sv: "reser", en: "travels" },
    { sv: "riktig", en: "real/proper" },
    { sv: "rädd", en: "afraid" },
    { sv: "räknar", en: "counts" },
    { sv: "(en) samhällskunskap", en: "social studies" },
    { sv: "sitter stilla", en: "sits still" },
    { sv: "sjunger", en: "sings" },
    { sv: "skolkar", en: "skips school" },
    { sv: "en slöfock", en: "a lazybones" },
    { sv: "springer", en: "runs" },
    { sv: "spännande", en: "exciting" },
    { sv: "sträng", en: "strict" },
    { sv: "svår", en: "difficult" },
    { sv: "särskilt", en: "especially" },
    { sv: "söker", en: "searches/applies" },
    { sv: "en termin", en: "a semester" },
    { sv: "tillbaka", en: "back" },
    { sv: "en tonåring", en: "a teenager" },
    { sv: "en tredjedel", en: "a third" },
    { sv: "en trumma", en: "a drum" },
    { sv: "en tröja", en: "a sweater" },
    { sv: "typisk", en: "typical" },
    { sv: "tänker", en: "thinks" },
    { sv: "ungefär", en: "approximately" },
    { sv: "en uppgift", en: "a task" },
    { sv: "ett uttryck", en: "an expression" },
    { sv: "varannan", en: "every other" },
    { sv: "viktig", en: "important" },
    { sv: "väldigt", en: "very" },
    { sv: "en ålder", en: "an age" },
    { sv: "en årskurs", en: "a school grade" },
    { sv: "älskar", en: "loves" },
    { sv: "ett ämne", en: "a subject" },
    { sv: "en översättare", en: "a translator" },
  ]},
  { chapter: 17, cards: [
    { sv: "en affisch", en: "a poster" },
    { sv: "antecknar", en: "takes notes" },
    { sv: "ett arbetsrum", en: "a workroom" },
    { sv: "ett badkar", en: "a bathtub" },
    { sv: "bakom", en: "behind" },
    { sv: "en bastu", en: "a sauna" },
    { sv: "en bokhylla", en: "a bookshelf" },
    { sv: "en bostad", en: "a home/residence" },
    { sv: "en bostadsrätt", en: "a condominium" },
    { sv: "ett bud", en: "a courier/bid" },
    { sv: "bygger", en: "builds" },
    { sv: "egen", en: "own" },
    { sv: "eldar", en: "makes a fire" },
    { sv: "fräsch", en: "fresh" },
    { sv: "funderar", en: "ponders" },
    { sv: "en fåtölj", en: "an armchair" },
    { sv: "en färg", en: "a color" },
    { sv: "förbereder", en: "prepares" },
    { sv: "en fördel", en: "an advantage" },
    { sv: "en förening", en: "an association" },
    { sv: "en förort", en: "a suburb" },
    { sv: "ett förråd", en: "a storage room" },
    { sv: "ett förstahandskontrakt", en: "a first-hand lease" },
    { sv: "en gardin", en: "a curtain" },
    { sv: "gemensam", en: "shared" },
    { sv: "gigantisk", en: "gigantic" },
    { sv: "ett golv", en: "a floor" },
    { sv: "en granne", en: "a neighbor" },
    { sv: "en gräsklippare", en: "a lawn mower" },
    { sv: "en hyresrätt", en: "a rental apartment" },
    { sv: "hållbar", en: "sustainable" },
    { sv: "hänger", en: "hangs" },
    { sv: "en högtalare", en: "a speaker" },
    { sv: "ett hörn", en: "a corner" },
    { sv: "inomhus", en: "indoors" },
    { sv: "en kompost", en: "a compost" },
    { sv: "en korridor", en: "a corridor" },
    { sv: "en krukväxt", en: "a potted plant" },
    { sv: "en kudde", en: "a pillow" },
    { sv: "en kvadratmeter", en: "a square meter" },
    { sv: "ett kylskåp", en: "a fridge" },
    { sv: "en källare", en: "a basement" },
    { sv: "ett köksskåp", en: "a kitchen cabinet" },
    { sv: "letar", en: "looks for" },
    { sv: "ett lånelöfte", en: "a loan promise" },
    { sv: "ett matbord", en: "a dining table" },
    { sv: "en matta", en: "a rug/carpet" },
    { sv: "en månadsavgift", en: "a monthly fee" },
    { sv: "en mäklare", en: "a real estate agent" },
    { sv: "en nackdel", en: "a disadvantage" },
    { sv: "nyrenoverad", en: "newly renovated" },
    { sv: "pendlar", en: "commutes" },
    { sv: "pigg", en: "alert/energetic" },
    { sv: "pysslar", en: "crafts/does crafts" },
    { sv: "ett radhus", en: "a townhouse" },
    { sv: "renoverar", en: "renovates" },
    { sv: "sambo", en: "cohabiting partner" },
    { sv: "en skrivbordslampa", en: "a desk lamp" },
    { sv: "ett skåp", en: "a cabinet" },
    { sv: "snygg", en: "good-looking" },
    { sv: "ett soffbord", en: "a coffee table" },
    { sv: "sparar", en: "saves" },
    { sv: "en spis", en: "a stove" },
    { sv: "spännande", en: "exciting" },
    { sv: "särbo", en: "living-apart partner" },
    { sv: "ett tak", en: "a roof/ceiling" },
    { sv: "en taklampa", en: "a ceiling lamp" },
    { sv: "en trädgård", en: "a garden" },
    { sv: "en tvättstuga", en: "a laundry room" },
    { sv: "en uteplats", en: "an outdoor area/patio" },
    { sv: "ett vardagsrum", en: "a living room" },
    { sv: "en visning", en: "a viewing" },
  ]},
  { chapter: 18, cards: [
    { sv: "annars", en: "otherwise" },
    { sv: "en anställning", en: "an employment" },
    { sv: "en apparat", en: "an appliance" },
    { sv: "en arbetsgivare", en: "an employer" },
    { sv: "en avdelning", en: "a department" },
    { sv: "ett betalkort", en: "a debit card" },
    { sv: "bjuder", en: "invites/treats" },
    { sv: "drar", en: "pulls" },
    { sv: "en fjärrkontroll", en: "a remote control" },
    { sv: "en fortbildning", en: "further training" },
    { sv: "en förkortning", en: "an abbreviation" },
    { sv: "ett förråd", en: "a storage room" },
    { sv: "föräldraledig", en: "on parental leave" },
    { sv: "en förändring", en: "a change" },
    { sv: "gnäller", en: "whines" },
    { sv: "(en) grädde", en: "cream" },
    { sv: "hemlig", en: "secret" },
    { sv: "häller", en: "pours" },
    { sv: "härlig", en: "lovely" },
    { sv: "hörlurar", en: "headphones" },
    { sv: "ett hörn", en: "a corner" },
    { sv: "en kabel", en: "a cable" },
    { sv: "en kanna", en: "a jug/pot" },
    { sv: "en karriär", en: "a career" },
    { sv: "en knapp", en: "a button" },
    { sv: "kommer på besök", en: "comes to visit" },
    { sv: "kontaktuppgifter", en: "contact details" },
    { sv: "kopplar in", en: "connects" },
    { sv: "krattar", en: "rakes" },
    { sv: "en kundtjänst", en: "customer service" },
    { sv: "en ledighet", en: "time off" },
    { sv: "en ledighetsansökan", en: "a leave application" },
    { sv: "en lön", en: "a salary" },
    { sv: "ett lösenord", en: "a password" },
    { sv: "en mall", en: "a template" },
    { sv: "ett meddelande", en: "a message" },
    { sv: "missar", en: "misses" },
    { sv: "en myndighet", en: "an authority" },
    { sv: "nedanför", en: "below" },
    { sv: "omkring", en: "around" },
    { sv: "planerar", en: "plans" },
    { sv: "ett protokoll", en: "minutes/protocol" },
    { sv: "ett påstående", en: "a statement" },
    { sv: "ett samtal", en: "a conversation" },
    { sv: "sjuk", en: "sick" },
    { sv: "en sjukdom", en: "a disease" },
    { sv: "skickar", en: "sends" },
    { sv: "en soffa", en: "a sofa" },
  ]},
];
